models:
    - name: dim_users
      description: "Contains dimensions for users"
      columns:
          - name: anonymous_user_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null